---
- name: Update all servers
  hosts: all

  tasks:
  - name: Update system
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 # 1 day
  
  - name: Git checkout
    git:
      repo: git@github.com:bakabtw/behemoth.payload.network.git
      dest: /opt/docker
      accept_hostkey: yes
      update: yes
      version: main

  - name: Pull docker images
    community.docker.docker_compose:
      project_src: /opt/docker/
      pull: true
      state: present
      remove_orphans: true
